# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
