# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0003_missions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missions',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
