# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0004_auto_20170715_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=0)),
                ('value', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='missions',
            name='ownerid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missions',
            name='period',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missions',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missions',
            name='type',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='missions',
            name='name',
            field=models.CharField(default='default', max_length=40),
        ),
    ]
